name: Build

on: [ push ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set version env
        run: echo "APP_VERSION=$(git describe --tags)" >> $GITHUB_ENV
      - name: Test
        run: echo $APP_VERSION

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker build -t chaosord/stakefish:$APP_VERSION .
          docker push chaosord/stakefish:$APP_VERSION

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Package
        run: |
          cd charts
          mkdir releases
          helm package -u -d ./releases --app-version $APP_VERSION
          git add ./releases
          git commit -m "publishing release $APP_VERSION"
          git push
      
