name: Release Package

on:
  push:
    tags:
      - '**'
jobs:
  release:
    name: Release Package
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set env variables
        run: |
          echo "APP_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Package
        run: |
          echo "CHART_VERSION=${APP_VERSION:1}" >> $GITHUB_ENV
          echo "Pushing helm chart package. APP_VERSION=$APP_VERSION CHART_VERSION=$CHART_VERSION"
          git config --global user.name 'Github action'
          git config --global user.email 'github-action@users.noreply.github.com'
          cd charts
          helm package -u -d ./releases --version $CHART_VERSION --app-version $APP_VERSION stakefish
          git add ./releases
          git commit -m "publishing release $APP_VERSION"
          git push

