name: Test

on: [ push ]

jobs:
  build:
    name: Integration Tests
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Run integration tests
        run: make test